"""In-memory runtime state for the agent API server.

Auto-generated by Forseti bundleBuilder (v1.3 — F2 template).

Production replaces with Postgres + Redis for multi-node deployments.
For dev / single-VM, in-memory is sufficient.

AUDIT HONESTY: non-authoritative in-memory observability cache — NOT
hash-linked and NOT tamper-proof. This deque is the volatile UI/observability
mirror, not the audit source; the durable hash-linked chain lives in HexaRecord
(src/shared/hexa_record.py, served at /api/audit).
"""
from __future__ import annotations

import asyncio
import threading
from collections import deque
from datetime import datetime, timezone
from typing import Any, Deque, Dict, List, Optional


class RuntimeState:
    """Thread-safe in-memory state. Methods are sync; broadcast uses asyncio.Queue."""

    def __init__(self, max_incidents: int = 1000, max_audit_entries: int = 10_000) -> None:
        self._lock = threading.Lock()
        self._incidents: Dict[str, Dict[str, Any]] = {}
        self._incident_order: Deque[str] = deque(maxlen=max_incidents)
        self._audit_chain: Deque[Dict[str, Any]] = deque(maxlen=max_audit_entries)
        self._subscribers: List[asyncio.Queue] = []
        self._stats: Dict[str, Any] = {
            "started_at": datetime.now(timezone.utc).isoformat(),
            "events_ingested": 0,
            "incidents_classified": 0,
            "auto_approved": 0,
            "pending_approval": 0,
            "escalated": 0,
            "denied": 0,
            "pii_blocks": 0,
            "errors": 0,
        }

    # ---- incidents ----
    def add_incident(self, event_id: str, incident: Dict[str, Any]) -> None:
        with self._lock:
            if event_id not in self._incidents and len(self._incident_order) >= (self._incident_order.maxlen or 0):
                evicted = self._incident_order.popleft() if self._incident_order else None
                if evicted and evicted in self._incidents:
                    del self._incidents[evicted]
            self._incidents[event_id] = incident
            if event_id not in list(self._incident_order):
                self._incident_order.append(event_id)

    def get_incident(self, event_id: str) -> Optional[Dict[str, Any]]:
        with self._lock:
            return self._incidents.get(event_id)

    def list_incidents(self, limit: int = 50, offset: int = 0) -> List[Dict[str, Any]]:
        with self._lock:
            ordered = list(self._incident_order)
        ordered.reverse()
        slice_ = ordered[offset:offset + limit]
        result = []
        with self._lock:
            for eid in slice_:
                inc = self._incidents.get(eid)
                if inc:
                    payload = inc.get("payload") or {}
                    plan = inc.get("plan") or {}
                    report = inc.get("report") or {}
                    result.append({
                        "event_id": eid,
                        "ts": inc.get("ts"),
                        "incident_type": payload.get("incident_type"),
                        "severity_level": payload.get("severity_level"),
                        "severity_score": payload.get("severity_score"),
                        "confidence": payload.get("confidence"),
                        "report_id": report.get("report_id"),
                        "verdict": inc.get("verdict"),
                        "blocked": inc.get("blocked", False),
                        "requires_approval": plan.get("requires_approval", False),
                    })
        return result

    def incident_count(self) -> int:
        with self._lock:
            return len(self._incidents)

    # ---- audit chain ----
    def append_audit(self, entry: Dict[str, Any]) -> None:
        with self._lock:
            self._audit_chain.append(entry)

    def list_audit(self, event_id: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
        with self._lock:
            if event_id:
                filtered = [e for e in self._audit_chain if e.get("event_id") == event_id]
                return filtered[-limit:]
            return list(self._audit_chain)[-limit:]

    # ---- stats ----
    def get_stats(self) -> Dict[str, Any]:
        with self._lock:
            return {
                **self._stats,
                "incident_count": len(self._incidents),
                "audit_chain_size": len(self._audit_chain),
                "active_subscribers": len(self._subscribers),
            }

    def inc_stat(self, key: str, delta: int = 1) -> None:
        with self._lock:
            self._stats[key] = int(self._stats.get(key, 0)) + delta

    # ---- SSE subscribers ----
    def subscribe(self) -> asyncio.Queue:
        q: asyncio.Queue = asyncio.Queue(maxsize=100)
        with self._lock:
            self._subscribers.append(q)
        return q

    def unsubscribe(self, q: asyncio.Queue) -> None:
        with self._lock:
            if q in self._subscribers:
                self._subscribers.remove(q)

    def broadcast(self, event: Dict[str, Any]) -> None:
        with self._lock:
            subs = list(self._subscribers)
        for q in subs:
            try:
                q.put_nowait(event)
            except asyncio.QueueFull:
                pass  # drop on backpressure

    def reset(self) -> None:
        with self._lock:
            self._incidents.clear()
            self._incident_order.clear()
            self._audit_chain.clear()
            self._subscribers.clear()
            self._stats = {
                "started_at": datetime.now(timezone.utc).isoformat(),
                "events_ingested": 0,
                "incidents_classified": 0,
                "auto_approved": 0,
                "pending_approval": 0,
                "escalated": 0,
                "denied": 0,
                "pii_blocks": 0,
                "errors": 0,
            }


_STATE = RuntimeState()


def get_state() -> RuntimeState:
    return _STATE


def reset_state() -> None:
    _STATE.reset()
