"""Runtime<->karta ORDER parity (CORE_DOCTRINE_REMINDER §3).

Auto-generated by Forseti bundleBuilder. Fail-capable doctrine gate: every
privileged approval/release/command gate that the karta places upstream of
egress (gate.XO -> egress.XI) MUST have its primary-path handle_xi realised in
run_pipeline BEFORE egress's handle_xi. If a generator change ever regresses
the gate-before-egress ordering, THIS TEST FAILS.
"""
import json
import re
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[2]
_PRIV = ("approval_gate", "release_gate", "command_generator")


def _topology():
    k = json.loads((BUNDLE_ROOT / "karta.compiled.json").read_text())
    return k.get("topology", {}).get("edges", []), k.get("topology", {}).get("nodes", [])


def _pe(e):
    sa, sp = e.get("source_agent"), e.get("source_port")
    ta, tp = e.get("target_agent"), e.get("target_port")
    if sa and ta:
        return sa, (sp or ""), ta, (tp or "")
    f, t = e.get("from", ""), e.get("to", "")
    sf, st = f.rsplit(".", 1), t.rsplit(".", 1)
    return sf[0], (sf[1] if len(sf) > 1 else ""), st[0], (st[1] if len(st) > 1 else "")


def _body():
    src = (BUNDLE_ROOT / "runtime" / "api_server.py").read_text()
    return src.split('@app.get("/healthz")')[0]


def _xi_pos(body, node):
    m = re.search(r"r_\S+ = await " + re.escape(node) + r"\.handle_xi\(", body)
    return m.start() if m else None


def test_every_gate_realised_before_egress():
    """Fas 3 · Delsteg 2b (H_ACTION_SELECTION): a privileged gate must be
    REACHABLE before egress — not unconditionally executed. On a selector karta
    the gate is realised inside the selector routing block
    (`if _sel_route == "<gate>":`), which itself must precede egress. On a
    non-selector karta the legacy primary-path ordering still applies."""
    edges, nodes = _topology()
    egress = [n["id"] for n in nodes if n.get("role") == "egress"]
    body = _body()
    selectors = [n["id"] for n in nodes
                 if (n.get("metadata") or {}).get("element_role") == "action_selector"]
    for eg in egress:
        eg_pos = _xi_pos(body, eg)
        if eg_pos is None:
            continue
        gates = {a for e in edges for a, ap, b, bp in [_pe(e)]
                 if b == eg and ap == "XO" and bp == "XI" and any(p in a for p in _PRIV)}
        for g in sorted(gates):
            gp = _xi_pos(body, g)
            assert gp is not None, f"{g}.XO->{eg}.XI declared but {g}.handle_xi not REACHABLE in run_pipeline (§3)"
            assert gp < eg_pos, f"{g}.handle_xi is realised AFTER {eg} — violates §3 (gate before egress)"
            if selectors:
                guard = re.search(r'if _sel_route == "' + re.escape(g) + r'"', body)
                assert guard is not None, (
                    f"{g}.handle_xi is realised UNCONDITIONALLY — it must only run when the "
                    f"ActionProposal selects it (H_ACTION_SELECTION)")
                assert guard.start() < gp < eg_pos, (
                    f"{g}.handle_xi is not inside its selector routing block before {eg}")
