"""Topology parity — orchestrator EXPECTED_BRANCHES must match the karta.

Auto-generated by Forseti bundleBuilder (PG-2). Derivation contract (shared
with the generator and the HexaBox Purity Gate detector): the number of
parallel branches equals the largest count of DISTINCT target nodes fanned
out from a single node's XO port; a fan-out of 0 or 1 means a serial map
and derives to 0 branches.

If you edit karta.yaml (and regenerate karta.compiled.json) or
src/shared/orchestrator.py by hand, this test keeps the two honest.
"""
import json
import re
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[2]


def _derive_parallel_branches(edges: list) -> int:
    """Mirror of the generator's deriveExpectedBranches (bundleBuilder.ts).

    An X-COMPUTE branch is a NON-ROUTING XO->XI edge. Routing edges belong to
    an action_selector subgraph (exactly ONE fires per event) and XO->MI/YI/ZI
    are M-plane redistribution / side-feeds — none of them are parallel
    branches. Keep this byte-aligned with deriveExpectedBranches and the
    Purity Gate detector."""
    fan_out: dict = {}
    for edge in edges:
        if not isinstance(edge, dict):
            continue
        source = edge.get("source_agent")
        source_port = str(edge.get("source_port") or "")
        target = edge.get("target_agent")
        target_port = str(edge.get("target_port") or "")
        if not source or not target or source_port.upper() != "XO" or target_port.upper() != "XI":
            continue
        if str(edge.get("kind") or "") == "routing":
            continue
        fan_out.setdefault(source, set()).add(target)
    best = max((len(targets) for targets in fan_out.values()), default=0)
    return best if best >= 2 else 0


def _load_edges() -> list:
    compiled = json.loads((BUNDLE_ROOT / "karta.compiled.json").read_text())
    return compiled.get("topology", {}).get("edges", [])


def test_expected_branches_matches_karta_topology():
    derived = _derive_parallel_branches(_load_edges())

    orchestrator_src = (BUNDLE_ROOT / "src" / "shared" / "orchestrator.py").read_text()
    match = re.search(r"EXPECTED_BRANCHES\s*=\s*(-?\d+)", orchestrator_src)
    assert match, "src/shared/orchestrator.py must declare EXPECTED_BRANCHES"
    literal = int(match.group(1))

    assert literal == derived, (
        f"orchestrator EXPECTED_BRANCHES={literal} but the karta derives "
        f"{derived} parallel branch(es) — regenerate the bundle"
    )


def test_parallel_maps_ship_a_barrier_helper():
    """Parallel maps must run branches concurrently; serial maps must not pay for a barrier."""
    derived = _derive_parallel_branches(_load_edges())
    orchestrator_src = (BUNDLE_ROOT / "src" / "shared" / "orchestrator.py").read_text()
    if derived > 0:
        assert "async def run_branches" in orchestrator_src
        assert "asyncio.gather" in orchestrator_src
    else:
        assert "async def run_branches" not in orchestrator_src
