"""End-to-end: POST /api/events drives the karta-derived pipeline.

Auto-generated by Forseti bundleBuilder (PG-3). Node ids, the ingress sample
event and branch expectations are interpolated from the ACTUAL karta topology
and its canonical schemas — never from legacy fixture ids.
"""
import time

import pytest
from fastapi.testclient import TestClient

from runtime.api_server import app

INGRESS_NODE_ID = "hexaforge_slm_training_master_intake_octa"

# Fas 3 · Delsteg 2b — selector facts, always defined so the cementing tests
# below run unchanged on a NON-selector agent (empty lineup = legacy semantics).
ACTION_SELECTOR_ID = "hexaforge_slm_training_master_action_selector_hexa"
ACTION_GATE_IDS = ["hexaforge_slm_training_master_bind_adapter_to_fleet_agent_approval_gate_hexa","hexaforge_slm_training_master_delete_artifact_approval_gate_hexa","hexaforge_slm_training_master_deny_bind_approval_gate_hexa","hexaforge_slm_training_master_grant_shared_adapter_training_approval_gate_hexa","hexaforge_slm_training_master_issue_delegation_grant_approval_gate_hexa","hexaforge_slm_training_master_keep_parked_approval_gate_hexa","hexaforge_slm_training_master_kill_job_approval_gate_hexa","hexaforge_slm_training_master_park_job_approval_gate_hexa","hexaforge_slm_training_master_pause_campaign_approval_gate_hexa","hexaforge_slm_training_master_promote_and_bind_adapter_approval_gate_hexa","hexaforge_slm_training_master_remove_flagged_rows_and_recheck_approval_gate_hexa","hexaforge_slm_training_master_requeue_job_approval_gate_hexa","hexaforge_slm_training_master_resume_campaign_approval_gate_hexa","hexaforge_slm_training_master_retry_with_adjustment_approval_gate_hexa","hexaforge_slm_training_master_revoke_delegation_grant_approval_gate_hexa","hexaforge_slm_training_master_rollback_binding_approval_gate_hexa","hexaforge_slm_training_master_rollback_fleet_binding_approval_gate_hexa","hexaforge_slm_training_master_start_training_job_approval_gate_hexa","hexaforge_slm_training_master_trigger_retrain_approval_gate_hexa"]


@pytest.fixture
def client():
    return TestClient(app)


def _sample_event(event_id: str = "evt-test-001"):
    """Derived from the ingress node's canonical XI schema (A1): POST /api/events
    validates against the SAME Pydantic model as /<ingress>/port-xi."""
    event = dict({})
    event["event_id"] = event_id
    # A1 platform envelope floor: /api/events requires a non-empty 'source'.
    event.setdefault("source", "pipeline-e2e-test")
    return event


def test_pipeline_e2e_completes_within_barrier_budget(client):
    """A single event must traverse the full karta pipeline within BARRIER_TIMEOUT_MS.

    A6: a bundle whose CUSTOMER_SLOTs are unimplemented reports an explicit
    degraded verdict with the blocking capabilities named — never a false "ok".
    """
    start = time.time()
    response = client.post("/api/events", json=_sample_event())
    elapsed_ms = (time.time() - start) * 1000.0
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("status") in ("ok", "degraded_blocking_stub"), response.text
    if body.get("status") == "degraded_blocking_stub":
        assert body.get("blocking_capabilities"), body
        assert body.get("payload") is None or body.get("degraded") is True, body
        # Fas 2.2c — degraded är entydigt fail-closed, aldrig releasebart.
        assert body.get("disposition") == "hold", body
        assert body.get("release_allowed") is False, body
    assert elapsed_ms < 5000, f"pipeline exceeded barrier budget ({elapsed_ms:.0f}ms)"


def test_api_events_rejects_contract_invalid_body(client):
    """A1 — the default ingress path enforces the ingress XI contract: a body
    that violates it is rejected 422 and never runs the pipeline."""
    response = client.post("/api/events", json={"definitely_not": ["a", "valid", "event"]})
    assert response.status_code in (200, 422), response.text
    if response.status_code == 200:
        pytest.skip("ingress XI contract has no required fields to violate")


def test_ingress_port_xi_responds(client):
    """Fas 2.1 — a contract-valid, attributable event is accepted AND the
    ENVELOPE survives the route: returned event_id/source are the caller's,
    never regenerated, never defaulted."""
    event = _sample_event("evt-test-003")
    event["source"] = "mail-gateway"
    response = client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event)
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("reason") != "ingress_envelope_invalid", body
    if body.get("ok") is True:
        assert body.get("event_id") == "evt-test-003", body
        assert body.get("source") == "mail-gateway", body


def _assert_ingress_rejected(response):
    """Fas 2.1 — governed rejection at the ingress node: HTTP 200 carrying
    ok=False / blocked=True / reason=ingress_envelope_invalid (never a crash)."""
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("ok") is False, body
    assert body.get("blocked") is True, body
    assert body.get("reason") == "ingress_envelope_invalid", body


def test_ingress_port_xi_rejects_missing_source(client):
    """Attribution can never be fabricated: a source-less event is rejected."""
    event = _sample_event("evt-floor-101")
    event.pop("source", None)
    _assert_ingress_rejected(client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event))


def test_ingress_port_xi_rejects_blank_source(client):
    """A blank source is as unattributable as a missing one (trim before check)."""
    event = _sample_event("evt-floor-102")
    event["source"] = "   "
    _assert_ingress_rejected(client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event))


def test_ingress_port_xi_rejects_blank_platform_fields(client):
    """event_id/ts are platform-assigned ONLY when absent — present-but-blank
    is a caller error and is never healed."""
    for field in ("event_id", "ts"):
        event = _sample_event("evt-floor-103")
        event["source"] = "mail-gateway"
        event[field] = "  "
        _assert_ingress_rejected(client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event))


def test_api_events_rejects_blank_platform_fields(client):
    """/api/events enforces the SAME floor — the two ingress doors are
    semantically identical (Fas 2.1)."""
    for field in ("event_id", "ts"):
        event = _sample_event("evt-floor-104")
        event[field] = ""
        assert client.post("/api/events", json=event).status_code == 422


def test_quickstart_sample_event_is_accepted(client):
    """Fas 2.2 — README<->testsvit-paritet: det DOKUMENTERADE quickstart-
    exemplet (demo/sample_event.json, EXAKT fil) måste passera ingress-
    kontraktet. README och testsviten kan aldrig mer glida isär."""
    import json as _json
    with open("demo/sample_event.json") as _f:
        sample = _json.load(_f)
    response = client.post("/api/events", json=sample)
    assert response.status_code != 422, (
        f"quickstart-exemplet avvisas av sitt eget kontrakt: {response.text}"
    )
    assert response.status_code == 200, response.text


def test_object_payload_accepted_at_ingress(client):
    """Fas 2.2 — ett realistiskt event med OBJEKT-payload accepteras och
    payloaden bevaras (kuvertmodellen: payload är dict, aldrig string)."""
    event = _sample_event("evt-object")
    event["source"] = "mail-gateway"
    event["payload"] = {"subject": "test"}
    response = client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event)
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("ok") is True, body
    assert body.get("event_id") == "evt-object", body
    assert body.get("payload") == {"subject": "test"}, body


def test_api_events_ts_is_backfilled_never_null(client):
    """Fas 2.2b — ett event UTAN ts måste få en riktig tidsstämpel tillbaka:
    plattformen tilldelar ts när fältet saknas, den returnerar ALDRIG null.
    (Regressionen: kuvert-mergen dumpade frånvarande fält som None.)"""
    event = _sample_event("evt-ts-events-001")
    event.pop("ts", None)
    response = client.post("/api/events", json=event)
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("ts"), f"ts ska plattformstilldelas, fick: {body.get('ts')!r}"
    assert body.get("event_id"), body


def test_ingress_port_xi_ts_is_backfilled_never_null(client):
    """Fas 2.2b — samma garanti på ingress-nodens egen dörr: dörrarna är
    semantiskt identiska (Fas 2.1), så ts-tilldelningen gäller BÅDA."""
    event = _sample_event("evt-ts-xi-001")
    event.pop("ts", None)
    response = client.post("/hexaforge_slm_training_master_intake_octa/port-xi", json=event)
    assert response.status_code == 200, response.text
    body = response.json()
    assert body.get("reason") != "ingress_envelope_invalid", body
    if body.get("ok") is True:
        assert body.get("ts"), body


EXPECTED_BRANCH_NODES = ["hexaforge_slm_training_master_enrichment_hexa","hexaforge_slm_training_master_model_freshness_validator_hexa","hexaforge_slm_training_master_packager_hexa","hexaforge_slm_training_master_safety_validator_hexa"]


def test_pipeline_e2e_all_branches_executed(client):
    """The karta declares parallel branches — the composite must prove that
    every branch actually executed before the barrier released. A bundle whose
    CUSTOMER_SLOTs are still scaffolds stops at the first BLOCKING stub (A6):
    that is an honest degraded verdict, not a branch regression."""
    response = client.post("/api/events", json=_sample_event("evt-test-002"))
    assert response.status_code == 200, response.text
    body = response.json()
    if body.get("status") == "degraded_blocking_stub":
        assert body.get("blocking_capabilities"), body
        # Fas 2.2c — degraded är entydigt fail-closed, aldrig releasebart.
        assert body.get("disposition") == "hold", body
        assert body.get("release_allowed") is False, body
        pytest.skip("unimplemented CUSTOMER_SLOT: pipeline degraded before the barrier")
    assert body.get("branches") == EXPECTED_BRANCH_NODES, body
    assert body.get("partial") is not True, "barrier must not time out on the happy path"


def test_pipeline_routes_privileged_actions_through_ccas(client):
    """S2/F3-1 + Fas 3 · Delsteg 2b (H_ACTION_SELECTION): on the default
    /api/events path, governed_actions carries EXACTLY the action(s) the typed
    ActionProposal selected — zero or one per event — NEVER every declared gate.
    No privileged gate may run without a matching proposal. Agents with no
    action_selector keep the legacy semantics (each gate on the primary path is
    CCAS-routed). Agents with no privileged actions skip."""
    body = client.post("/api/events", json=_sample_event("evt-gov-001")).json()
    governed = body.get("governed_actions") or []
    routing = body.get("action_routing")
    if routing is not None:
        # Selector agent: at most ONE gate executed, and it is the routed one.
        routed = routing.get("routed_to")
        ran = [g.get("node") for g in governed if g.get("node") in ACTION_GATE_IDS]
        assert len(ran) <= 1, (ran, routing)
        if routed is None:
            assert ran == [], ("no proposal selected a gate, yet a gate ran", ran)
        else:
            assert ran in ([], [routed]), (ran, routed)
        for skipped in routing.get("skipped", []):
            assert skipped not in ran, ("non-selected gate ran", skipped, ran)
    if not governed:
        pytest.skip("no privileged action was selected for this event")
    assert all(g.get("ccas_decision") for g in governed), governed
    for g in governed:
        # A2: "executed" follows the REAL side effect, not the gate's ok flag.
        # An unwired _apply_ seam is approved-but-not-executed, and must say so.
        assert g.get("executed") is not True or (g.get("ccas_decision") or {}).get("status") == "approved", g
        if (g.get("ccas_decision") or {}).get("tier") == "tier_4":
            assert g["executed"] is False and g["status"] == "pending_dual_approval", g


def test_zero_trust_fails_closed_by_default(client):
    """Fas 2.5 (A3): transport auth is FAIL-CLOSED — ZT_REQUIRE_AUTH UNSET
    means ON: every non-health endpoint 401s without a credential while
    /healthz stays open for liveness probes. The ONLY open mode is the
    explicit dev opt-out ZT_REQUIRE_AUTH=0 (conftest sets it VISIBLY for
    this suite; src/main.py's serve_guard confines it to loopback binds)."""
    import os

    assert client.get("/healthz").status_code == 200
    os.environ.pop("ZT_REQUIRE_AUTH", None)  # UNSET => fail-closed ON
    try:
        assert client.get("/healthz").status_code == 200
        assert client.get("/api/autonomy").status_code == 401
        assert client.post("/api/events", json=_sample_event("evt-zt-001")).status_code == 401
    finally:
        os.environ["ZT_REQUIRE_AUTH"] = "0"  # restore the suite's explicit dev opt-out
    # Explicit dev opt-out => open again (dev on loopback only, per serve_guard).
    assert client.get("/api/autonomy").status_code == 200


def test_zero_trust_authenticated_caller_passes(client):
    """Fas 2.5: fail-closed är inte lock-out — a caller with a valid bearer
    token in ZT_IDENTITIES passes (200); a wrong token stays 401."""
    import json as _json
    import os

    os.environ["ZT_REQUIRE_AUTH"] = "1"
    os.environ["ZT_IDENTITIES"] = _json.dumps({
        "zt-test-token": {"identity": "ops@zt-test", "scopes": ["autonomy:read"], "expires_at": None},
    })
    try:
        assert client.get("/api/autonomy").status_code == 401
        ok = client.get("/api/autonomy", headers={"Authorization": "Bearer zt-test-token"})
        assert ok.status_code == 200, ok.text
        assert client.get(
            "/api/autonomy", headers={"Authorization": "Bearer wrong-token"}
        ).status_code == 401
    finally:
        os.environ["ZT_REQUIRE_AUTH"] = "0"
        os.environ.pop("ZT_IDENTITIES", None)


def test_serve_guard_refuses_open_nonloopback():
    """Fas 2.5 (A3 serve-guard, enda källan src.shared.zt_auth): with auth
    explicitly OFF a non-loopback bind refuses to start; loopback is allowed
    (dev); auth ON allows any bind. Both entrypoints route through it."""
    import os

    import pytest as _pytest

    from src.shared.zt_auth import serve_guard

    os.environ["ZT_REQUIRE_AUTH"] = "0"
    try:
        serve_guard("127.0.0.1")  # auth off + loopback: tillåtet (dev)
        with _pytest.raises(SystemExit):
            serve_guard("0.0.0.0")  # auth off + öppet interface: VÄGRA
        os.environ["ZT_REQUIRE_AUTH"] = "1"
        serve_guard("0.0.0.0")  # auth på: valfri bind
    finally:
        os.environ["ZT_REQUIRE_AUTH"] = "0"

    # Båda entrypoints går genom vakten (importbara, guard-anropet i källan).
    import inspect

    from runtime import serve as _serve
    from src import main as _main

    assert "serve_guard(host)" in inspect.getsource(_serve)
    assert "serve_guard(host)" in inspect.getsource(_main)


def test_zero_trust_covers_stream_and_ingest(client):
    """A3 coverage: the SSE incident feed and the per-node /port-xi ingest
    routes carry the SAME Zero Trust posture as /api/incidents and /api/events.
    Neither may be reachable unauthenticated when ZT_REQUIRE_AUTH is on."""
    import os

    os.environ["ZT_REQUIRE_AUTH"] = "1"
    try:
        assert client.get("/api/events/stream").status_code == 401
        assert client.post(
            "/hexaforge_slm_training_master_intake_octa/port-xi", json=_sample_event("evt-zt-002")
        ).status_code == 401
    finally:
        os.environ["ZT_REQUIRE_AUTH"] = "0"  # Fas 2.5: tillbaka till svitens EXPLICITA dev-opt-out


def test_audit_chain_binds_principal_and_exact_input(client):
    """Fas 2.11a — AUDIT BINDING e2e: an authenticated /api/events call leaves
    chain entries whose HASHED core carries (a) the verified caller identity on
    EVERY entry of the event (contextvar inheritance — pipeline sites and
    in-node log_event calls alike), and (b) at the ingress step, the canonical
    hash of the EXACT event the handler received — recomputed here from the
    posted body byte-for-byte. verify_chain stays green, so all of it is
    tamper-evident, not annotation."""
    import json as _json
    import os

    from src.shared.hexa_record import canonical_sha256, read_chain_for_event, verify_chain

    os.environ["ZT_REQUIRE_AUTH"] = "1"
    os.environ["ZT_IDENTITIES"] = _json.dumps({
        "audit-bind-token": {"identity": "auditor@zt-test", "scopes": ["events:write"], "expires_at": None},
    })
    try:
        body = _sample_event("evt-audit-bind-001")
        # Pin ts explicitly: the platform heals a MISSING ts (Fas 2.2b), and a
        # healed field would make the outside recompute diverge from the exact
        # dict the handler received. With both set, healing is a no-op.
        body.setdefault("ts", "2026-08-03T12:00:00+00:00")
        response = client.post(
            "/api/events", json=body,
            headers={"Authorization": "Bearer audit-bind-token"},
        )
        assert response.status_code == 200, response.text
        entries = read_chain_for_event("evt-audit-bind-001")
        assert entries, "an audited pipeline run must leave chain entries"
        # WHO — every entry for this event carries the verified identity.
        for e in entries:
            assert e.get("principal") == "auditor@zt-test", e
        # WHAT-IN — the ingress step binds the EXACT posted event (event_id +
        # ts are set in the sample, so the platform heals nothing).
        ingress_entries = [
            e for e in entries
            if e.get("node_id") == INGRESS_NODE_ID and e.get("port") == "xi" and "input_sha256" in e
        ]
        assert ingress_entries, entries
        assert ingress_entries[-1]["input_sha256"] == canonical_sha256(body)
        # WHAT-OUT — bound at the same step (exact-output equality is proven
        # against the returned body in the /port-xi test below).
        out = ingress_entries[-1].get("output_sha256")
        assert isinstance(out, str) and len(out) == 64, ingress_entries[-1]
        assert verify_chain() is True
    finally:
        os.environ["ZT_REQUIRE_AUTH"] = "0"
        os.environ.pop("ZT_IDENTITIES", None)


def test_audit_chain_binds_exact_output_on_node_route(client):
    """Fas 2.11a — the per-node route returns the handler result VERBATIM, so
    the chain's output_sha256 must equal the canonical hash of the HTTP
    response body — exact-output binding, recomputed from the outside. The
    input binding is recomputed through the SAME merge the route performs
    (envelope + validated payload). With the suite's explicit dev opt-out
    (ZT_REQUIRE_AUTH=0) the principal is the honest marker "auth_disabled" —
    attribution is never silently absent."""
    from src.shared.contracts import HexaforgeSlmTrainingMasterIntakeOctaXiSchema
    from src.shared.hexa_record import canonical_sha256, read_chain_for_event

    body = _sample_event("evt-audit-bind-002")
    body.setdefault("ts", "2026-08-03T12:00:00+00:00")
    response = client.post(f"/{INGRESS_NODE_ID}/port-xi", json=body)
    assert response.status_code == 200, response.text
    entries = [
        e for e in read_chain_for_event("evt-audit-bind-002")
        if e.get("node_id") == INGRESS_NODE_ID and e.get("port") == "xi" and "output_sha256" in e
    ]
    assert entries, "the /port-xi route must bind its audit entry"
    entry = entries[-1]
    assert entry["output_sha256"] == canonical_sha256(response.json())
    merged = {**body, **HexaforgeSlmTrainingMasterIntakeOctaXiSchema(**body).model_dump(mode="json", exclude_none=True)}
    assert entry["input_sha256"] == canonical_sha256(merged)
    assert entry.get("principal") == "auth_disabled"


def test_correlation_chain_preserves_request_id(client):
    """Fas 2.11b — correlation chain (external assessment #4, finding D): the
    ingress ACCEPTED request_id but the field vanished from pipeline and audit.
    Now: the composite carries a correlation block (event_id / request_id /
    source / ts / principal), it rides the response, and the caller's
    request_id is bound into the audit entries' HASHED core."""
    from src.shared.hexa_record import read_chain_for_event, verify_chain

    body = _sample_event("evt-corr-001")
    body.setdefault("ts", "2026-08-03T12:00:00+00:00")
    body["request_id"] = "req-e2e-42"
    response = client.post("/api/events", json=body)
    assert response.status_code == 200, response.text
    corr = response.json().get("correlation")
    assert corr, "composite must carry the correlation block"
    assert corr["event_id"] == "evt-corr-001"
    assert corr["request_id"] == "req-e2e-42"
    assert corr["source"] == body["source"]
    assert corr["ts"] == body["ts"]
    # Suite default is the explicit dev opt-out — attribution is the honest
    # marker, never silently missing.
    assert corr["principal"] == "auth_disabled"
    entries = read_chain_for_event("evt-corr-001")
    assert entries, "pipeline must audit"
    for e in entries:
        assert e.get("request_id") == "req-e2e-42", e
    assert verify_chain() is True


def test_correlation_maps_absent_request_id_to_explicit_none(client):
    """Fas 2.11b — absence is a VISIBLE mapping: no request_id in the event
    means correlation.request_id is an explicit None in the composite, and the
    audit core honestly omits the key (never a fabricated value)."""
    from src.shared.hexa_record import read_chain_for_event

    body = _sample_event("evt-corr-002")
    body.pop("request_id", None)
    response = client.post("/api/events", json=body)
    assert response.status_code == 200, response.text
    corr = response.json().get("correlation")
    assert corr and "request_id" in corr and corr["request_id"] is None
    for e in read_chain_for_event("evt-corr-002"):
        assert "request_id" not in e, e


def test_ingestion_policy_enforced_at_the_door(client):
    """Fas 2.11c — ingestion_policy is WIRED, not decorative (external
    assessment #4, finding B): the composed door enforces caller-set event_id
    dedup (409 on a repeat) and the source allowlist (403 when configured and
    the source is unknown; unset = allow-all, dev default unchanged)."""
    import os

    from src.shared.ingestion_policy import reset_ingestion_state

    body = _sample_event("evt-ingest-dedup-001")
    first = client.post("/api/events", json=body)
    assert first.status_code == 200, first.text
    second = client.post("/api/events", json=body)
    assert second.status_code == 409, second.text
    assert "duplicate event_id" in second.json()["detail"]
    reset_ingestion_state()  # polite: leave no cross-test dedup residue

    os.environ["INGEST_ALLOWED_SOURCES"] = "trusted-gateway"
    try:
        blocked = client.post("/api/events", json=_sample_event("evt-ingest-src-001"))
        assert blocked.status_code == 403, blocked.text
        assert "source_not_allowed" in blocked.json()["detail"]
        ok = _sample_event("evt-ingest-src-002")
        ok["source"] = "trusted-gateway"
        allowed = client.post("/api/events", json=ok)
        assert allowed.status_code == 200, allowed.text
    finally:
        os.environ.pop("INGEST_ALLOWED_SOURCES", None)
        reset_ingestion_state()


def test_module_truth_reflects_measured_imports(client):
    """Fas 2.11c — module_truth.json is MEASURED status (finding E): every
    src/shared module carries 'active' (imported by an emitted runtime
    surface) or 'generated_unbound' (visibly not wired — never active-looking).
    ingestion_policy must be active now that the door enforces it, and the
    file's statuses must agree with a live import re-scan of api_server."""
    import inspect
    import json as _json

    from runtime import api_server as _api

    with open("module_truth.json") as f:
        truth = _json.load(f)
    by_name = {m["module"]: m for m in truth["modules"]}
    assert by_name["ingestion_policy"]["status"] == "active", by_name["ingestion_policy"]
    assert "runtime/api_server.py" in by_name["ingestion_policy"]["imported_by_runtime"]
    src = inspect.getsource(_api)
    assert "from src.shared.ingestion_policy import" in src
    assert truth["total"] == truth["active"] + truth["generated_unbound"]
    for m in truth["modules"]:
        assert m["status"] in ("active", "generated_unbound"), m
        assert (m["status"] == "active") == (len(m["imported_by_runtime"]) > 0), m
    # Fas 2.11h — deployment-grade är SKÖRDAD ur modulens egna konstanter:
    # liggaren måste vara paritetsexakt med källan (aldrig dubbeldeklarerad).
    from src.shared import ingestion_policy as _ip
    grade = by_name["ingestion_policy"].get("declared_grade") or {}
    assert grade.get("dedup_backend") == _ip.DEDUP_BACKEND == "in_memory", grade
    assert grade.get("deployment_grade") == _ip.DEPLOYMENT_GRADE == "local_single_process", grade
    assert grade.get("customer_binding_required_for") == _ip.CUSTOMER_BINDING_REQUIRED_FOR, grade
    # Fas 2.11h — varje obunden modul förklarar sig: why + binding_required.
    for m in truth["modules"]:
        if m["status"] == "generated_unbound":
            d = m.get("disposition") or {}
            assert d.get("why") and d.get("binding_required"), m
    # docs-spegeln är genererad ur samma objekt och nämner varje modul.
    with open("docs/module-status.md") as f:
        doc = f.read()
    for m in truth["modules"]:
        assert m["module"] in doc, m["module"]
    assert "Why unbound:" in doc


def test_selector_invokes_exactly_one_gate(client):
    """Fas 3: the ActionProposal router must execute AT MOST ONE privileged
    gate per event — never the unconditional fan-out this replaced. Every
    non-selected candidate must be reported as deliberately skipped."""
    response = client.post("/api/events", json=_sample_event("evt-sel-001"))
    assert response.status_code == 200, response.text
    body = response.json()
    if body.get("status") == "degraded_blocking_stub":
        # Fas 2.2c — degraded är entydigt fail-closed, aldrig releasebart.
        assert body.get("disposition") == "hold", body
        assert body.get("release_allowed") is False, body
        pytest.skip("unimplemented CUSTOMER_SLOT: pipeline degraded before the selector")
    routing = body.get("action_routing")
    assert routing is not None, body
    assert routing["selector"] == ACTION_SELECTOR_ID
    assert routing["candidates"] == ACTION_GATE_IDS
    routed = routing.get("routed_to")
    assert routed is None or routed in ACTION_GATE_IDS, routing
    expected_skipped = [g for g in ACTION_GATE_IDS if g != routed]
    assert routing["skipped"] == expected_skipped, routing
    assert len(ACTION_GATE_IDS) - len(routing["skipped"]) <= 1, routing


def test_unknown_action_is_fail_closed():
    """Fas 3: an action with no registered gate must NEVER bypass the gate.
    The routing table only maps DECLARED privileged actions, and run_pipeline
    aborts the event with status 'unroutable_action' on a miss."""
    import inspect

    from runtime import api_server

    assert api_server._ACTION_ROUTES, "selector karta must ship a routing table"
    for action, gate in api_server._ACTION_ROUTES.items():
        assert gate in ACTION_GATE_IDS, (action, gate)
    assert api_server._ACTION_ROUTES.get("definitely_not_a_declared_action") is None
    source = inspect.getsource(api_server.run_pipeline)
    assert "unroutable_action" in source, "fail-closed branch missing from run_pipeline"
