"""HexaBox anonymization — PII-doctrine + per-karta contract enforcement.

Auto-generated by Forseti bundleBuilder (v1.3 — F12 template).

Universal FAIL-block: the ten FORBIDDEN_PII_KEYS below MUST NEVER appear
on any Mo egress payload, regardless of what the karta's
anonymization_contract permits. This is the doctrine floor — the karta
contract can only narrow it further, never widen.

Scan is recursive: dicts and lists are walked all the way down. A single
hit raises PIILeakError, which the Mo port_zo wrapper converts into a
502 Bad Gateway so the caller can see the failure shape.
"""
from typing import Any


# ──────────────────────────────────────────────────────────────
# F12 — Universal PII-doctrine (Forseti v1.3, lifted from Eihwaz EIH-309)
# These 10 keys MUST NEVER leak through any Mo egress in any HexaBox agent.
# ──────────────────────────────────────────────────────────────
FORBIDDEN_PII_KEYS: frozenset = frozenset(["user_id","tenant_id","raw_prompt","email","session_id","ip_address","prompt_text","answers","agent_id","karta_yaml"])


class PIILeakError(ValueError):
    """Raised when a payload contains a forbidden PII key or violates the
    per-karta anonymization_contract. The Mo port wrapper translates this
    into a structured 502 response with the violating path attached."""


def _scan_for_pii(value: Any, path: str = '$') -> None:
    """Recursive PII scan. Walks dicts and lists; raises PIILeakError on
    the first forbidden key found. Path is reported for debuggability."""
    if isinstance(value, dict):
        for k, v in value.items():
            if k in FORBIDDEN_PII_KEYS:
                raise PIILeakError(
                    f"PII-doctrine violation at {path}.{k} — "
                    f"forbidden key '{k}' detected in Mo egress"
                )
            _scan_for_pii(v, f"{path}.{k}")
    elif isinstance(value, list):
        for i, item in enumerate(value):
            _scan_for_pii(item, f"{path}[{i}]")
    # primitives (str, int, float, bool, None) — nothing to scan


# No anonymization_contract authored on the karta — only the universal
# PII-doctrine floor applies.
def _enforce_karta_contract(payload: dict) -> None:
    return None


def enforce_contract(payload: dict) -> None:
    """Enforce both the PII-doctrine (universal) and the per-karta
    anonymization_contract (if authored). Order matters: doctrine first
    so karta contracts can never weaken the floor."""
    if not isinstance(payload, dict):
        raise PIILeakError(f"enforce_contract expects dict payload, got {type(payload).__name__}")
    _scan_for_pii(payload)
    _enforce_karta_contract(payload)


# ──────────────────────────────────────────────────────────────
# T-04-015 — Non-raising collector for runtime enforcement.
# Reuses the SAME FORBIDDEN_PII_KEYS doctrine floor as _scan_for_pii,
# but instead of raising on the first hit it walks the whole structure
# and returns the list of offending key-paths. The anonymization node
# uses this to decide the reject_and_alert verdict (N5) without
# control-flow-by-exception, and to know EVERY leaked key (not just the
# first) for the alert.
# ──────────────────────────────────────────────────────────────
def collect_pii_paths(value: Any, path: str = "$") -> list:
    """Recursively walk `value` and return every key-path whose dict key is
    in the canonical FORBIDDEN_PII_KEYS set. Non-raising counterpart of
    _scan_for_pii. Returns [] when the payload is clean."""
    hits: list = []
    if isinstance(value, dict):
        for k, v in value.items():
            if k in FORBIDDEN_PII_KEYS:
                hits.append(f"{path}.{k}")
            hits.extend(collect_pii_paths(v, f"{path}.{k}"))
    elif isinstance(value, list):
        for i, item in enumerate(value):
            hits.extend(collect_pii_paths(item, f"{path}[{i}]"))
    # primitives — nothing to scan
    return hits
