"""CCAS gate for privileged actions on Yo ports.

Auto-generated by Forseti bundleBuilder (v1.3 — F13 template).

WHAT THIS IS (Fas 2.13c, external DD honesty): a CCAS *tier-enforcement
interface* and a *fail-closed approval seam* — NOT a finished approvals system.
It classifies an action's tier and, for tiers that require human sign-off, only
transitions to "approved" when it is handed approvals that are STRUCTURALLY
VALID and provenance-verified: each approval must be a record bound to THIS
action (action_ref), carry an approver role, use a fresh nonce (anti-replay),
and be signed by the customer's approval backend. That signature is verified by
verify_approval_signature(), whose trust root (CCAS_APPROVAL_KEY) is a
CUSTOMER_SLOT: with no key bound, NO approval verifies and every gated tier
parks fail-closed. A bare name (e.g. "alice") counts for NOTHING. Binding a real
approval backend (issuing signed, role-scoped, action-bound approvals) is the
customer's step.

Fas 2.17 — persistent anti-replay: an approval that has RELEASED an action is
CONSUMED in the append-only ledger (src/shared/approval_ledger.py) BEFORE
"approved" is returned, and a consumed (action_ref, approver, nonce) tuple can
never release again - not in this call, not in a later one. An unwritable
ledger withholds the release (fail-closed); an unreadable ledger invalidates
every approval (freshness cannot be proven). Explicit expires_at on an approval
is honored fail-closed. The local file is the SKELETON ledger; bind a shared
store for multi-replica production (CUSTOMER step, like hexa_record's
DATABASE_URL).

Decision shape (stable contract — consumed by every action_proposer-class
node and audited via HexaRecord H7):
  {
    "status":  "approved" | "pending" | "escalated"
               | "pending_dual_approval" | "denied",
    "tier":    "tier_1" | "tier_2" | "tier_3" | "tier_4" | "<legacy>",
    "route":   "emit" | "approval_queue" | "escalation_topic"
               | "dual_approval_queue" | "drop",
    "reason":  <human-readable string>,
  }
"""
import hashlib
import hmac
import json
import os
import time
import unicodedata
from typing import Any

from src.shared import approval_ledger
from src.shared.canonical_identity import canonical_identity as _canonical_identity


# ── Fas 2.13c — approval provenance (fail-closed seam) ─────────────────────
# The cryptographic trust root for approvals is a CUSTOMER_SLOT. With no key
# bound, verify_approval_signature() returns False for everything, so no gated
# tier can ever transition to "approved" — the default skeleton is fail-closed.
CCAS_APPROVAL_KEY = os.environ.get("CCAS_APPROVAL_KEY", "")
# Roles allowed to approve. A record whose role is not here counts for nothing.
CCAS_APPROVER_ROLES = frozenset(
    r.strip() for r in os.environ.get("CCAS_APPROVER_ROLES", "approver,dual_approver,admin").split(",")
    if r.strip()
)


# Fas 2.22 (external DD, Peter #1 — confused deputy): the immutable semantic
# fields of an ActionProposal that DECIDE what will happen. The approval binds
# to a hash over THESE, never to a mutable correlation id (request_id) — so
# swapping any of them after an approval was issued breaks every signature.
_CANONICAL_ACTION_FIELDS = (
    "selected_action",
    "target_asset",
    "action_parameters",
    "policy_requirements",
    "tenant_id",
    "tier",
    "idempotency_key",
)

# Fas 3.2 (external DD, major) — the tenant used to be listed here as "tenant"
# while every contract, the runtime and the audit chain carried "tenant_id". The
# field LOOKED bound and never was: two proposals differing only in tenant_id
# hashed identically, so an approval issued for one tenant was cryptographically
# valid for another. Names are normalised HERE, once, so an upstream that says
# either one still binds — and always under the canonical key.
_TENANT_KEYS = ("tenant_id", "tenant")


# Fas 3.11 (adversarial finding) — CANONICAL IDENTITY.
# tier_4 dual approval was satisfied by "alice" and "Alice " — the same human,
# spelled two ways, counted as two independent approvers. Demonstrated on the
# real signed bundle. Any identity that participates in a QUORUM or in the
# SIGNED hash must therefore be compared in one canonical form: NFKC (so
# homoglyph and width variants collapse), stripped, case-folded. Applied to
# approver, role and tenant, and applied BEFORE both the hash and the count —
# normalising in only one of the two places would just move the hole.
# Fas 3.25 — re-exported from the shared module so the gate, the audit chain and
# the execution ledger cannot drift apart on what one identity is.
canonical_identity = _canonical_identity


def action_tenant(action: Any) -> str:
    """The action's tenant, normalised. Empty string when absent/blank."""
    if not isinstance(action, dict):
        return ""
    for key in _TENANT_KEYS:
        val = action.get(key)
        if val is None or isinstance(val, (dict, list)):
            continue
        canon = canonical_identity(val)
        if canon:
            return canon
    return ""


def canonical_action_ref(action: Any) -> str:
    """The stable, CONTENT-BOUND id an approval is cryptographically pinned to.

    Fas 2.22 (external DD, Peter #1): the ref is a SHA-256 over the immutable
    semantic content of the action — the exact fields that decide WHAT will
    happen (selected_action, target_asset, action_parameters, policy_requirements,
    tenant, tier, idempotency_key) — NOT a mutable correlation id (request_id).
    Because the approval signature binds this ref (see _canonical_approval_msg),
    changing ANY of those fields after an approval was issued changes the ref and
    breaks every signature: a valid approval for one action body can never be
    replayed onto a different body (the confused-deputy hole). An action carrying
    NONE of these fields yields "" (fail-closed: an unidentified action cannot be
    approved). The hash is computed over a canonical JSON (sorted keys, tight
    separators) so it is deterministic across processes and re-serialisations."""
    if not isinstance(action, dict):
        return ""
    core = {k: action[k] for k in _CANONICAL_ACTION_FIELDS if action.get(k) is not None}
    # Fas 3.2 — bind the tenant under ONE canonical key regardless of which name
    # the caller used, so the hash cannot be dodged by a rename upstream.
    tenant = action_tenant(action)
    if tenant:
        core["tenant_id"] = tenant
    if not core:
        return ""  # no semantic content to bind — fail closed
    canonical = json.dumps(core, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _action_ref(action: Any) -> str:
    """The stable id an approval must be bound to (anti confused-deputy /
    cross-action replay). Fas 2.22: this is now the CONTENT-bound
    canonical_action_ref (a hash over the action's immutable semantic fields),
    NOT a request_id. Unidentified action => "" => nothing can approve it."""
    return canonical_action_ref(action)


def _canonical_approval_msg(action_ref: str, approver: str, role: str, nonce: str, expires_at: Any = None) -> bytes:
    """The exact bytes the approval backend signs — binds approver + role + THIS
    action + a fresh nonce so a signature cannot be replayed onto another action.
    Fas 2.17: when the backend issues an expiry, expires_at is PART of the signed
    bytes — stripping or altering it breaks the signature (str(expires_at)
    verbatim as sent). Approvals without expiry keep the 4-field format."""
    # Fas 3.11 — the SIGNED bytes bind the canonical spelling, so a signature
    # issued for "Alice " cannot be presented as a second, different approver.
    base = "%s|%s|%s|%s" % (action_ref, canonical_identity(approver),
                            canonical_identity(role), nonce)
    if expires_at is not None and str(expires_at) != "":
        base = base + "|" + str(expires_at)
    return base.encode("utf-8")


# Fas 3.7 (adversarial finding) — APPROVAL SOVEREIGNTY.
# With a shared HMAC secret the party that VERIFIES an approval can also MINT
# one: the key sits in the agent's own environment, so a compromised agent
# process (or anyone who can read its env) can sign "two independent approvals"
# for its own tier_4 action. Demonstrated on a real bundle: dual_approval
# returned "approved" for approvals minted inside the agent. That defeats
# separation of duties, which is the entire point of the tier ladder.
#
# The fix is asymmetric: the APPROVER signs with a private key that never exists
# on this host, and the agent verifies with a PUBLIC key. Then the agent
# structurally cannot mint what it checks.
#
#   CCAS_APPROVAL_PUBKEYS  JSON {"<approver_principal>": "<base64 ed25519 pub>"}
#                          (or a single base64 key used for every approver)
#
# When pubkeys are bound, the HMAC path is REFUSED — a fallback that a caller
# can select is not a fallback, it is the hole. When they are not bound, HMAC
# still works (dev/legacy) but every decision DISCLOSES that its approvals are
# self-mintable, so the artifact never claims a property it does not have.
CCAS_APPROVAL_PUBKEYS = os.environ.get("CCAS_APPROVAL_PUBKEYS", "")


def _approval_pubkey_map():
    raw = CCAS_APPROVAL_PUBKEYS.strip()
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except (ValueError, TypeError):
        return {"*": raw}  # a bare key string applies to every approver
    if isinstance(data, dict):
        return {str(k): str(v) for k, v in data.items()}
    return {}


# Fas 3.13 — tolerance for legitimate backward clock steps (NTP correction,
# VM resume). An attacker rolling the clock back to revive an expired approval
# needs minutes-to-hours, not seconds, so a small window costs nothing. It IS a
# boundary: approvals whose lifetime is shorter than this window cannot be
# protected by the ratchet, which is why it is named, defaulted conservatively
# and settable rather than hidden inside a comparison.
CCAS_CLOCK_SKEW_TOLERANCE_S = float(os.environ.get("CCAS_CLOCK_SKEW_TOLERANCE_S", "120") or 120)


def clock_trust() -> str:
    """Whether the local clock can be trusted to judge approval freshness.

    "monotonic_ok"      - the clock is at or ahead of every timestamp the
                          append-only approval ledger has ever recorded.
    "rollback_detected" - the clock reads BEFORE the ledger's high-water mark
                          by more than the skew tolerance. Something moved time
                          backwards; expiry checks are meaningless and the gate
                          must not release.
    "no_high_water"     - the ledger has recorded nothing yet, so there is no
                          floor to compare against. Rollback is UNDETECTABLE
                          here. Disclosed, never assumed away.
    "ledger_unreadable" - the floor cannot be established at all.
    """
    try:
        floor = approval_ledger.high_water_ts()
    except Exception:  # noqa: BLE001
        return "ledger_unreadable"
    if not floor:
        return "no_high_water"
    if time.time() + CCAS_CLOCK_SKEW_TOLERANCE_S < floor:
        return "rollback_detected"
    return "monotonic_ok"


def approval_trust() -> str:
    """How much an approval is worth on THIS deployment. Reported in every
    decision so the posture is never implicit."""
    if _approval_pubkey_map():
        return "asymmetric"
    if CCAS_APPROVAL_KEY:
        return "shared_secret_self_mintable"
    return "unbound"


def _ed25519_ok(pub_b64: str, signature: str, msg: bytes) -> bool:
    """Verify with the bundle's OWN audited pure-python Ed25519 (emitted as a
    shared runtime module), so neither a root CLI script nor a new dependency
    enters the runtime import graph."""
    try:
        import base64 as _b64

        from src.shared.ed25519_verify import ed25519_verify as _verify
        try:
            sig = bytes.fromhex(signature)
        except ValueError:
            sig = _b64.b64decode(signature)
        return bool(_verify(_b64.b64decode(pub_b64), sig, msg))
    except Exception:  # noqa: BLE001 - any failure is a failed verification
        return False


def verify_approval_signature(approval: Any, action_ref: str) -> bool:
    """CUSTOMER_SLOT — prove the approval was issued by the customer's approval
    backend. PREFERRED: Ed25519 against CCAS_APPROVAL_PUBKEYS (the agent holds
    no private key and therefore cannot mint). FALLBACK: HMAC-SHA256 with
    CCAS_APPROVAL_KEY, accepted ONLY when no pubkeys are bound and disclosed as
    self-mintable. FAIL-CLOSED: with neither bound this returns False, so the
    default package approves nothing."""
    if not isinstance(approval, dict):
        return False
    sig = approval.get("signature")
    if not isinstance(sig, str) or not sig:
        return False
    pubkeys = _approval_pubkey_map()
    if pubkeys:
        approver = str(approval.get("approver_principal") or "")
        role = str(approval.get("role") or "")
        nonce = str(approval.get("nonce") or "")
        pub = pubkeys.get(approver) or pubkeys.get("*")
        if not pub:
            return False  # an approver with no registered key approves nothing
        return _ed25519_ok(
            pub, sig,
            _canonical_approval_msg(action_ref, approver, role, nonce, approval.get("expires_at")),
        )
    if not CCAS_APPROVAL_KEY:
        return False
    sig = approval.get("signature")
    if not isinstance(sig, str) or not sig:
        return False
    approver = str(approval.get("approver_principal") or "")
    role = str(approval.get("role") or "")
    nonce = str(approval.get("nonce") or "")
    expected = hmac.new(
        CCAS_APPROVAL_KEY.encode("utf-8"),
        _canonical_approval_msg(action_ref, approver, role, nonce, approval.get("expires_at")),
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(sig, expected)


def _not_expired(approval: Any) -> bool:
    """Fas 2.17 — honor an EXPLICIT expires_at on the approval record.
    Absent => no expiry (documented boundary). Present => must parse (epoch
    seconds or ISO-8601) and lie in the future; malformed => invalid
    (fail-closed). The approval backend decides whether to issue expiries."""
    exp = approval.get("expires_at")
    if exp is None:
        return True
    try:
        if isinstance(exp, (int, float)) and not isinstance(exp, bool):
            deadline = float(exp)
        else:
            from datetime import datetime, timezone
            dt = datetime.fromisoformat(str(exp))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            deadline = dt.timestamp()
    except (ValueError, TypeError):
        return False  # malformed expiry — fail closed
    return time.time() < deadline


def _valid_approvals(action: Any) -> list:
    """The structured approval RECORDS that are valid for THIS action. An
    approval only counts when it is a structured record (a bare name counts for
    NOTHING), carries an approver role, is bound to this action's ref, uses a
    not-yet-seen nonce (anti-replay within the set), is NOT expired, is NOT
    already consumed in the persistent ledger (Fas 2.17 — anti-replay ACROSS
    calls: an approval that released an action once can never release another),
    and is signature-verified (fail-closed when CCAS_APPROVAL_KEY is unset)."""
    if not isinstance(action, dict):
        return []
    raw = action.get("approvals")
    if not isinstance(raw, (list, tuple)):
        return []
    action_ref = _action_ref(action)
    if not action_ref:
        return []  # cannot bind approvals to an unidentified action — fail closed
    valid: list = []
    used_nonces: set = set()
    for item in raw:
        if not isinstance(item, dict):
            continue  # bare strings (e.g. "alice") never count
        approver = str(item.get("approver_principal") or "")
        role = str(item.get("role") or "")
        nonce = str(item.get("nonce") or "")
        if not approver or not nonce:
            continue
        if role not in CCAS_APPROVER_ROLES:
            continue  # not an approver role
        if str(item.get("action_ref") or "") != action_ref:
            continue  # not bound to THIS action
        if nonce in used_nonces:
            continue  # replayed nonce (within this request)
        if not _not_expired(item):
            continue  # expired or malformed expiry (fail-closed)
        if approval_ledger.is_consumed(action_ref, approver, nonce):
            continue  # already released an action once (persistent anti-replay)
        if not verify_approval_signature(item, action_ref):
            continue  # unsigned / bad signature / no backend key (fail-closed)
        used_nonces.add(nonce)
        valid.append(item)
    return valid


def dual_approval_trust(action: Any) -> str:
    """How INDEPENDENT the approvers on this action actually are.

    Fas 3.37 (external DD, trust boundary) — SAY WHAT THE QUORUM MEANS.

    tier_4 counts DISTINCT approver principals, which is correct as far as it
    goes. But a single wildcard public key verifies every principal: whoever
    holds that one external private key can produce two principal entries and
    satisfy the quorum alone. That is not necessarily wrong — the key may belong
    to an approval service that authenticates two humans itself — but then the
    guarantee is "two principals attested by ONE external authority", not "two
    cryptographically independent signatories".

    Blocking the wildcard would break a legitimate deployment. Silently calling
    it independent would overclaim. So the posture is stamped on the decision,
    the way every other unprovable-here property is:

      independent_keys  every approver resolved to their OWN registered key
      single_authority  at least one resolved via the wildcard, so one key
                        stands behind more than one principal
      shared_secret     no pubkeys bound at all (HMAC fallback; the agent can
                        mint what it verifies — see approval_trust())
      unbound           no approval backend bound; nothing releases
    """
    pubkeys = _approval_pubkey_map()
    if not pubkeys:
        return "shared_secret" if os.environ.get("CCAS_APPROVAL_KEY") else "unbound"
    named = 0
    wildcarded = 0
    for a in _valid_approvals(action):
        approver = canonical_identity(a.get("approver_principal"))
        if pubkeys.get(approver):
            named += 1
        elif pubkeys.get("*"):
            wildcarded += 1
    if wildcarded:
        return "single_authority"
    return "independent_keys" if named else "unbound"


def _valid_approver_principals(action: Any) -> set:
    """The set of DISTINCT authenticated approver principals whose approvals
    are valid for THIS action (see _valid_approvals). Independence is enforced
    by de-duplicating on approver_principal."""
    return {canonical_identity(a.get("approver_principal")) for a in _valid_approvals(action)}


def _consume_for_release(action: Any, valid: list) -> dict | None:
    """Fas 2.17/2.22 — atomically consume the EXACT valid approval set the tier
    branch decided on, BEFORE a release. Returns None only when THIS call is the
    sole releaser: it durably wrote EVERY tuple in the valid set itself. Any of —
    an empty set, a ledger failure, or one/more tuples already consumed by a
    concurrent or prior release (approval_ledger.consume writes fewer than
    len(valid)) — returns a fail-closed HOLD decision dict. This is what makes an
    approval single-use under concurrency: two callers racing to release the same
    action both pass the tier threshold, but the atomic ledger lets only one of
    them write the tuples, so only that one releases (no double release)."""
    if not valid:
        return {
            "status": "pending",
            "route": "approval_queue",
            "reason": "no fresh approvals to consume — release withheld (single-use, fail-closed)",
        }
    try:
        written = approval_ledger.consume(_action_ref(action), valid)
    except approval_ledger.LedgerUnavailable as e:
        return {
            "status": "pending",
            "route": "approval_queue",
            "reason": "approval ledger unavailable — release withheld (fail-closed): %s" % e,
        }
    if written < len(valid):
        return {
            "status": "pending",
            "route": "approval_queue",
            "reason": "approvals already consumed by a concurrent/prior release — withheld (single-use, fail-closed)",
        }
    return None


# Canonical tier names (Forseti v1.3 CCAS doctrine)
TIER_1 = "tier_1"  # auto-execute — low blast radius, reversible, signed
TIER_2 = "tier_2"  # analyst approval — medium blast radius, manual gate
TIER_3 = "tier_3"  # multi-party / admin — high blast radius, freeze + escalate
TIER_4 = "tier_4"  # dual approval — strictest: TWO independent approvers required

# Strictness ladder (ascending). TIER_4 is the strictest tier — a TIER_4 action
# can NEVER auto-approve and can NEVER be dropped; it parks pending until two
# INDEPENDENT approvals are recorded.
TIER_STRICTNESS = {TIER_1: 1, TIER_2: 2, TIER_3: 3, TIER_4: 4}

# Number of distinct, independent approver identities a TIER_4 (dual_approval)
# action requires before it may transition to "approved". Two is the doctrinal
# floor for the strictest tier; a single approver — even repeated — is NOT enough.
TIER_4_REQUIRED_APPROVALS = 2

# Fas 2.22 (external DD, Peter #4): TIER_3 is declared "multi-party / admin",
# but it used to release on ANY single ordinary approver. A TIER_3 action now
# requires EITHER a valid approval from an ADMIN role, OR at least
# TIER_3_MIN_APPROVALS independent approver identities. One ordinary approver is
# never enough. CCAS_ADMIN_ROLES is a CUSTOMER_SLOT (which of the customer's
# approver roles count as "admin"); it must be a subset of CCAS_APPROVER_ROLES
# for such an approval to be structurally valid in the first place.
TIER_3_MIN_APPROVALS = 2
CCAS_ADMIN_ROLES = frozenset(
    r.strip() for r in os.environ.get("CCAS_ADMIN_ROLES", "admin").split(",")
    if r.strip()
)

# Legacy / external aliases (still seen in older kartas + tier_policy values —
# normalise on read so a declared tier always maps to a canonical TIER_n).
_LEGACY_TIER_MAP = {
    "auto":          TIER_1,
    "manual":        TIER_2,
    "human":         TIER_3,
    "dual_approval": TIER_4,
    "t1":            TIER_1,
    "t2":            TIER_2,
    "t3":            TIER_3,
    "t4":            TIER_4,
}


def _normalise_tier(tier: str) -> str:
    """Map legacy/alias tier names to canonical tier_1..tier_4."""
    if tier in (TIER_1, TIER_2, TIER_3, TIER_4):
        return tier
    return _LEGACY_TIER_MAP.get(tier, tier)


def _independent_approvals(action: Any) -> int:
    """Count DISTINCT, provenance-verified, action-bound approver identities.

    Fas 2.13c: this now delegates to _valid_approver_principals — a bare name
    counts for NOTHING; an approval must be a structured record bound to THIS
    action, carry an approver role, use a fresh nonce, and be signature-verified
    (fail-closed when CCAS_APPROVAL_KEY is unset). Independence de-dupes on the
    approver principal, so one person can never satisfy dual approval alone."""
    return len(_valid_approver_principals(action))


def ccas_decide(action: Any, tier: str) -> dict:
    """Decide, then DISCLOSE the approval posture on every path.

    Fas 3.7 — the trust posture is stamped by this wrapper rather than at each
    return, because the branch that actually released tier_4 was the one that
    got missed when the field was added by hand. A property that must hold on
    every path should be applied on every path, once."""
    clock = clock_trust()
    # DD P0 (fleet) — capability-lease enforcement at the ONE choke point every
    # privileged action already passes (same all-paths principle as Fas 3.7).
    # When this runtime is a fleet member (FLEET_LEASE_REQUIRED truthy) a valid,
    # unexpired, signature-verified capability lease is REQUIRED before any
    # privileged action is even considered; missing/expired/invalid DENIES
    # fail-closed. No development default key exists — a missing key is a deny.
    # DD P0 FTC-3: enforcement is MANDATORY for a fleet-managed member, decided
    # by the runtime's own signed identity (fleet_trust.fleet_managed) — NOT by
    # an operator env flag that no delivered deployment sets. A fleet-managed
    # agent with absent/broken lease infrastructure fail-closes here; the lease
    # is checked for the SPECIFIC capability this action needs (its
    # selected_action name), so a lease scoped to other capabilities does not
    # authorise this one (FTC-2 scope binding, enforced end-to-end).
    from src.shared.fleet_trust import fleet_managed, require_fleet_lease
    if fleet_managed():
        _capability = ""
        if isinstance(action, dict):
            _capability = str(action.get("selected_action") or action.get("name")
                              or action.get("action") or action.get("type") or "")
        _lease_ok, _lease_reasons = require_fleet_lease(_capability)
        if not _lease_ok:
            return {
                "status": "denied",
                "tier": _normalise_tier(tier),
                "route": "fleet_lease_gate",
                "reason": "fleet capability lease invalid or absent for '%s': %s" % (
                    _capability or "<unnamed action>", ", ".join(_lease_reasons)),
                "approval_trust": approval_trust(),
                "clock_trust": clock,
            }
    decision = _ccas_decide(action, tier)
    if isinstance(decision, dict):
        decision.setdefault("approval_trust", approval_trust())
        decision.setdefault("clock_trust", clock)
        # Fas 3.13 — a released decision rests on expires_at, and expires_at
        # rests on the clock. With the clock proven to have moved backwards the
        # freshness verdict is worthless, so the release is withheld rather
        # than granted on evidence we know is unreliable. Refusing here (after
        # the decision, on the wrapper) covers every branch that can release,
        # for the same reason approval_trust is stamped here.
        if clock == "rollback_detected" and decision.get("status") == "approved":
            return {
                "status": "pending",
                "tier": decision.get("tier"),
                "route": "approval_queue",
                "reason": ("clock rollback detected: the system clock reads before the approval "
                           "ledger's high-water mark, so approval freshness (expires_at) cannot "
                           "be judged; release withheld"),
                "approval_trust": decision.get("approval_trust"),
                "clock_trust": clock,
            }
    return decision


def _ccas_decide(action: Any, tier: str) -> dict:
    """Decide whether an action emitted on a Yo port can proceed,
    must wait for analyst approval, must escalate to a human, or — for the
    strictest tier_4 (dual_approval) — must park pending until two independent
    approvals are recorded.

    Fas 2.22: every decision carries "action_ref" — the CONTENT hash the
    approvals are bound to (canonical_action_ref). The executor re-derives it
    before applying the side effect, so the action executed is byte-identical to
    the action approved (no confused deputy at the executor boundary)."""
    canonical = _normalise_tier(tier)
    ref = _action_ref(action)
    # Fas 3.2 — an APPROVAL-BEARING action must be tenant-scoped. A privileged
    # action nobody can attribute to a tenant must not be releasable: without a
    # tenant the approval binds nothing that isolates one customer from another.
    # tier_1 (auto, reversible, no approval) is deliberately unaffected.
    if canonical != TIER_1 and not action_tenant(action):
        return {
            "status": "pending",
            "tier": canonical,
            "route": "hold",
            "action_ref": ref,
            "reason": ("fail-closed: the action carries no tenant_id — a gated action must be "
                       "tenant-scoped before any approval can release it (Fas 3.2)"),
            "approval_trust": approval_trust(),
        }
    if canonical == TIER_1:
        return {
            "status": "approved",
            "tier": canonical,
            "route": "emit",
            "action_ref": ref,
            "reason": "tier_1: auto-execute (low blast radius, reversible)",
            "approval_trust": approval_trust(),
        }
    if canonical == TIER_2:
        valid = _valid_approvals(action)
        approvers = {canonical_identity(a.get("approver_principal")) for a in valid}
        if approvers:
            held = _consume_for_release(action, valid)  # Fas 2.17/2.22: atomic single-use before release
            if held is not None:
                held["tier"] = canonical
                held["action_ref"] = ref
                held["approval_trust"] = approval_trust()
                return held
            return {
                "status": "approved",
                "tier": canonical,
                "route": "emit",
                "action_ref": ref,
                "reason": "tier_2: analyst approval verified (%d provenance-valid, consumed in ledger)" % len(approvers),
                "approvals": len(approvers),
            }
        return {
            "status": "pending",
            "tier": canonical,
            "route": "approval_queue",
            "action_ref": ref,
            "reason": "tier_2: analyst approval required before emit (no provenance-verified approval yet)",
        }
    if canonical == TIER_3:
        # Fas 2.22 (Peter #4) — TIER_3 is "multi-party / admin". A single ORDINARY
        # approver must NOT release it. Release requires EITHER a valid approval
        # from an ADMIN role, OR at least TIER_3_MIN_APPROVALS independent
        # approver identities. This logic is EXECUTABLE here, not a comment.
        valid = _valid_approvals(action)
        principals = {canonical_identity(a.get("approver_principal")) for a in valid}
        admins = {canonical_identity(a.get("approver_principal")) for a in valid
                  if str(a.get("role") or "") in CCAS_ADMIN_ROLES}
        if admins or len(principals) >= TIER_3_MIN_APPROVALS:
            held = _consume_for_release(action, valid)  # Fas 2.17/2.22: atomic single-use before release
            if held is not None:
                held["tier"] = canonical
                held["action_ref"] = ref
                held["approval_trust"] = approval_trust()
                return held
            return {
                "status": "approved",
                "tier": canonical,
                "route": "emit",
                "action_ref": ref,
                "reason": "tier_3: multi-party/admin approval verified (%d independent principal(s)%s, consumed in ledger)"
                          % (len(principals), ", admin sign-off" if admins else ""),
                "approvals": len(principals),
            }
        return {
            "status": "escalated",
            "tier": canonical,
            "route": "escalation_topic",
            "action_ref": ref,
            "reason": "tier_3: multi-party / admin approval required — need an admin approver or >=%d independent approvers (have %d)"
                      % (TIER_3_MIN_APPROVALS, len(principals)),
            "approvals": len(principals),
        }
    if canonical == TIER_4:
        # Strictest tier (TIER_STRICTNESS[TIER_4] == 4). Dual approval: the action
        # NEVER auto-approves and is NEVER dropped — it parks pending in the
        # dual-approval queue until TWO INDEPENDENT approvers have signed. We
        # count distinct approver identities (a single approver, even repeated,
        # is insufficient); only the second independent signature flips it to
        # approved. This logic is EXECUTABLE here, not a comment.
        valid = _valid_approvals(action)
        approvals = _independent_approvals(action)
        if approvals >= TIER_4_REQUIRED_APPROVALS:
            held = _consume_for_release(action, valid)  # Fas 2.17/2.22: atomic single-use before release
            if held is not None:
                held["tier"] = canonical
                held["route"] = "dual_approval_queue"
                held["status"] = "pending_dual_approval"
                held["action_ref"] = ref
                return held
            return {
                "status": "approved",
                "tier": canonical,
                "route": "emit",
                "action_ref": ref,
                "reason": (
                    "tier_4: dual approval satisfied "
                    f"({approvals} independent approvals >= {TIER_4_REQUIRED_APPROVALS}, consumed in ledger)"
                ),
                "approvals": approvals,
                # Fas 3.37 — what the quorum actually guarantees here.
                "dual_approval_trust": dual_approval_trust(action),
            }
        return {
            "status": "pending_dual_approval",
            "tier": canonical,
            "route": "dual_approval_queue",
            "action_ref": ref,
            "reason": (
                "tier_4: dual approval required — "
                f"{approvals}/{TIER_4_REQUIRED_APPROVALS} independent approvals so far"
            ),
            "approvals": approvals,
            "dual_approval_trust": dual_approval_trust(action),
        }
    return {
        "status": "denied",
        "tier": tier,
        "route": "drop",
        "action_ref": ref,
        "reason": f"unknown tier: {tier!r}",
    }


def classify_action(action: Any, default_tier: str = TIER_2) -> str:
    """Best-effort tier classification. Handlers can override with their
    own logic; default policy is conservative (tier_2 — manual gate)."""
    if not isinstance(action, dict):
        return default_tier
    explicit = action.get("ccas_tier") or action.get("tier")
    if explicit:
        return _normalise_tier(str(explicit))
    # Heuristic: a few well-known blast-radius signals
    if action.get("scope") in ("fleet", "global", "tenant_wide"):
        return TIER_3
    if action.get("reversible") is True and action.get("scope") in ("single_host", "single_user"):
        return TIER_1
    return default_tier
