"""HexaLearn shared primitives — embedding + vector similarity.

Auto-generated by Forseti bundleBuilder (v1.3 — F3 template).

Reusable foundation for any node that needs semantic similarity over
event/incident data. Examples of consumers:
  - knowledge_hub_macrohub (cohort similarity search)
  - incident_correlator_hexa (per-event similarity)
  - any custom node imported via 'from src.shared.hexa_learn import ...'

Pluggable providers:
  - EmbeddingProvider — default is deterministic hash-based (free, fast,
    perfect H1 determinism, useful for tests + demos). Production swaps
    in Voyage AI / OpenAI text-embedding-3-small / Anthropic embeddings.
  - VectorIndex — default in-memory dict with cosine search; production
    swaps in pgvector-backed store via the same interface.
"""
from __future__ import annotations

import hashlib
import json
import math
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple


DEFAULT_EMBED_DIM = 384


# ----------------- Embedding providers -----------------

EmbeddingProviderFunc = Callable[[str], Awaitable[Tuple[List[float], Dict[str, Any]]]]
# Returns (vector, provenance_meta) — provenance_meta carries model_id, tokens, cost_usd


def hash_to_floats(text: str, dim: int = DEFAULT_EMBED_DIM) -> List[float]:
    """Deterministic hash-based embedding.

    Same text -> same L2-normalised vector. Not semantically meaningful —
    intended for tests, demos, and air-gapped fallback. Production swaps in
    a real embedding provider via the EmbeddingProvider interface.
    """
    out: List[float] = []
    seed = text.encode("utf-8")
    counter = 0
    while len(out) < dim:
        block = hashlib.sha256(seed + counter.to_bytes(4, "big")).digest()
        for i in range(0, len(block), 2):
            if len(out) >= dim:
                break
            raw = int.from_bytes(block[i:i + 2], "big", signed=False)
            out.append((raw / 65535.0) * 2.0 - 1.0)
        counter += 1
    norm = math.sqrt(sum(x * x for x in out)) or 1.0
    return [x / norm for x in out]


async def hash_embedding_provider(text: str) -> Tuple[List[float], Dict[str, Any]]:
    """Default async embedding provider — hash-based, deterministic."""
    vec = hash_to_floats(text, DEFAULT_EMBED_DIM)
    return vec, {
        "model_id": "stub-hash-embedding-v1",
        "input_tokens": max(1, len(text) // 4),
        "output_tokens": 0,
        "cost_usd": 0.0,
        "embedding_dim": DEFAULT_EMBED_DIM,
    }


# ----------------- Cosine similarity -----------------

def cosine_similarity(a: List[float], b: List[float]) -> float:
    """Cosine similarity. Returns dot product since inputs are L2-normalised."""
    if len(a) != len(b):
        return 0.0
    return sum(x * y for x, y in zip(a, b))


# ----------------- In-memory vector index -----------------

class VectorIndex:
    """In-memory vector index with cosine top-k search.

    Production replaces with pgvector wrapper. Interface required:
      add(item_id, vector, metadata)
      search(query_vector, top_k, threshold) -> list of {item_id, similarity, metadata}
      size()
      clear()
    """

    def __init__(self) -> None:
        self._items: Dict[str, Tuple[List[float], Dict[str, Any]]] = {}

    def add(self, item_id: str, vector: List[float], metadata: Optional[Dict[str, Any]] = None) -> None:
        self._items[item_id] = (vector, metadata or {})

    def remove(self, item_id: str) -> None:
        self._items.pop(item_id, None)

    def size(self) -> int:
        return len(self._items)

    def clear(self) -> None:
        self._items.clear()

    def search(
        self,
        query: List[float],
        top_k: int = 5,
        threshold: float = 0.0,
    ) -> List[Dict[str, Any]]:
        if not self._items:
            return []
        scored = [
            {
                "item_id": iid,
                "similarity": cosine_similarity(query, vec),
                "metadata": meta,
            }
            for iid, (vec, meta) in self._items.items()
        ]
        scored = [s for s in scored if s["similarity"] >= threshold]
        scored.sort(key=lambda s: s["similarity"], reverse=True)
        return scored[:top_k]


# ----------------- Helpers -----------------

def features_to_text(features: Dict[str, Any], stable_keys: Optional[Tuple[str, ...]] = None) -> str:
    """Convert a feature dict to a deterministic text representation for embedding.

    Keys are sorted (or use stable_keys order) so the same features always
    produce the same input string -> same vector via hash embedding.
    """
    if stable_keys:
        ordered = [(k, features.get(k)) for k in stable_keys if features.get(k) is not None]
    else:
        ordered = sorted(
            ((k, v) for k, v in features.items() if v is not None),
            key=lambda kv: kv[0],
        )
    return json.dumps(ordered, default=str)


def cohort_signature(item_ids: List[str], top_similarity: float) -> str:
    """Audit signature over a similarity-search result. Deterministic."""
    sig_input = "|".join(sorted(item_ids)) + f"|{top_similarity:.4f}"
    return hashlib.sha256(sig_input.encode()).hexdigest()
