"""Forseti re-generation helper — splice fresh AUTOGEN blocks into
existing handler.py files without losing customer code below the marker.

Usage::

    # Dry-run: print files that would be modified
    python -m services.forseti_regen --new-bundle ./fresh_bundle --dry-run

    # Apply: replace AUTOGEN blocks in src/nodes/*/handler.py
    python -m services.forseti_regen --new-bundle ./fresh_bundle

Generated by Forseti bundleBuilder (v1.3 — F16 template).

Contract:
  - Files with AUTOGEN markers → the block between START/END is replaced
    with the fresh version; everything below END is preserved verbatim.
  - Files without AUTOGEN markers (legacy / pre-v1.3 bundles) → the
    existing file is moved to handler.py.bak and the fresh file is
    written so the next regen is safe.
  - Files that exist in the fresh bundle but not the current tree are
    written as-is (new nodes added to karta).
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

AUTOGEN_START = "# FORSETI-AUTOGEN-START:"
AUTOGEN_END = "# FORSETI-AUTOGEN-END:"


def split_autogen(content: str) -> tuple[str | None, str | None, str | None]:
    """Return (header_before_start, autogen_block, customer_below_end).
    If no markers found, returns (content, None, None)."""
    if AUTOGEN_START not in content or AUTOGEN_END not in content:
        return content, None, None

    # Find the START line — split on it and keep header.
    start_idx = content.find(AUTOGEN_START)
    # Walk back to the previous blank line to capture the marker banner.
    head_break = content.rfind("\n", 0, start_idx) + 1
    # Find END line and walk forward through its banner.
    end_idx = content.find(AUTOGEN_END)
    end_line_end = content.find("\n", end_idx)
    # Find next blank line after the END banner block
    tail_start = content.find("\n", end_line_end + 1)
    # Skip remaining banner lines that start with '#'
    lines = content[end_line_end + 1:].splitlines(keepends=True)
    consumed = 0
    for line in lines:
        if line.startswith("#") or line.strip() == "":
            consumed += len(line)
        else:
            break
    customer_start = end_line_end + 1 + consumed
    header = content[:head_break]
    autogen = content[head_break:customer_start]
    customer = content[customer_start:]
    return header, autogen, customer


def splice(existing: str, fresh: str) -> tuple[str, str]:
    """Return (new_content, status). Status is 'spliced' / 'no_markers' / 'unchanged'."""
    _, fresh_block, _ = split_autogen(fresh)
    header, current_block, customer = split_autogen(existing)
    if fresh_block is None:
        # Fresh file has no markers — replace whole file.
        return fresh, "no_markers_in_fresh"
    if current_block is None:
        # Legacy file — no markers. Caller should back up + rewrite.
        return fresh, "legacy_no_markers"
    if current_block == fresh_block:
        return existing, "unchanged"
    new = (header or "") + fresh_block + (customer or "")
    return new, "spliced"


def apply(bundle_root: Path, fresh_root: Path, dry_run: bool = False) -> int:
    """Walk every src/nodes/<id>/handler.py in the fresh bundle and splice
    into the matching file under bundle_root. Returns a non-zero exit code
    if anything went wrong."""
    fresh_handlers = sorted((fresh_root / "src" / "nodes").glob("*/handler.py"))
    if not fresh_handlers:
        print(f"[forseti-regen] no handlers found under {fresh_root}", file=sys.stderr)
        return 2

    changed = 0
    spliced = 0
    legacy = 0
    new = 0
    unchanged = 0
    errors = 0

    for fresh_path in fresh_handlers:
        rel = fresh_path.relative_to(fresh_root)
        target = bundle_root / rel
        fresh = fresh_path.read_text()
        if not target.exists():
            print(f"[forseti-regen] NEW  {rel}")
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(fresh)
            new += 1
            changed += 1
            continue
        existing = target.read_text()
        new_content, status = splice(existing, fresh)
        if status == "unchanged":
            unchanged += 1
            continue
        if status == "spliced":
            print(f"[forseti-regen] SPLICE {rel}")
            spliced += 1
        elif status == "legacy_no_markers":
            print(f"[forseti-regen] LEGACY {rel} (existing → {rel}.bak)")
            legacy += 1
            if not dry_run:
                shutil.copy(target, target.with_suffix(target.suffix + ".bak"))
        else:
            print(f"[forseti-regen] ??? {rel} (status={status})", file=sys.stderr)
            errors += 1
        if not dry_run:
            target.write_text(new_content)
        changed += 1

    summary = (
        f"\n[forseti-regen] summary: "
        f"{spliced} spliced, {legacy} legacy-backup, {new} new, "
        f"{unchanged} unchanged, {errors} errors"
    )
    print(summary)
    return 0 if errors == 0 else 1


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m services.forseti_regen",
        description="Re-generate Forseti handlers while preserving customer code.",
    )
    p.add_argument("--new-bundle", required=True, type=Path,
                   help="path to freshly generated bundle (output of Forseti)")
    p.add_argument("--bundle-root", default=Path.cwd(), type=Path,
                   help="path to the existing bundle to update (default: cwd)")
    p.add_argument("--dry-run", action="store_true",
                   help="print what would change but write nothing")
    args = p.parse_args(argv)
    if not args.new_bundle.is_dir():
        print(f"[forseti-regen] --new-bundle not a directory: {args.new_bundle}",
              file=sys.stderr)
        return 2
    return apply(args.bundle_root.resolve(), args.new_bundle.resolve(),
                 dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
